### ISSUE TITLE
Transliterated application list

### ISSUE THREAD

**Issue by mymedia2** [ubuntu-mate/mate-menu#65] opened 2019-10-31 14:49 UTC
https://github.com/ubuntu-mate/mate-menu/blob/28c9fbb47bf7a3b0a28f8d119c84842a74ddf499/mate_menu/easybuttons.py#L401

unidecode turns Russian (or any non-Latin language) into unreadable mishmash. What is the general purpose of strip_accents? Can we completely remove it from the module?

Compare: on the first image how it looks at the moment, on the second image what I want to get.

![Снимок экрана в 2019-10-31 17-27-04](https://user-images.githubusercontent.com/9163157/67956975-f9f30480-fc05-11e9-8804-ffbef54dfe41.png)
![Снимок экрана в 2019-10-31 17-27-25](https://user-images.githubusercontent.com/9163157/67956994-024b3f80-fc06-11e9-98f7-4910bb5e5e0e.png)

**Comment by alkisg** [comment] 2020-01-31 07:03
I saw this with Greek locale too. It affects Ubuntu 19.10 and 20.04. The last good version was 19.04.

It's caused by this commit: https://github.com/ubuntu-mate/mate-menu/commit/28c9fbb47bf7a3b0a28f8d119c84842a74ddf499

In function strip_accents(), for some reason unidecode.unidecode(value) is now used, which is inappropriate.

For example, the Greek translation for "MATE Calculator" is "Αριθμομηχανή MATE" and that's what should show up in the menu. Yet, unidecode transliterates that to "Arithmomechane MATE".

@flexiondotorg, @vkareh, any input? Thank you.

**Comment by MikePooh** [comment] 2020-02-15 10:08
Can be fixed by replacing
`return unidecode.unidecode(value)`
to
`return value`
strip_accents() function in mate-menu/mate_menu/easybuttons.py

**Comment by flexiondotorg** [comment] 2020-02-15 10:45
Please could you submit a pull request?

**Closed** 2020-02-17 14:51 UTC
